Update action.yml

diff --git a/apply-failure/action.yml b/apply-failure/action.yml
--- a/apply-failure/action.yml
+++ b/apply-failure/action.yml
@@ -25,10 +25,10 @@ runs:
       working-directory: ${{ inputs.testing_path }}
       run: terraform apply -auto-approve -var "unix_interpreter=/bin/bash"
     - name: Check for Failure
-        if: steps.apply-bash.outcome != 'failure'
-        run: |
-          echo "Apply succeeded when it was expected to fail"
-          exit 1
+      if: steps.apply-bash.outcome != 'failure'
+      run: |
+        echo "Apply succeeded when it was expected to fail"
+        exit 1
 
     - name: Terraform Apply (dash)
       if: matrix.shells == 'true'
@@ -38,10 +38,10 @@ runs:
       working-directory: ${{ inputs.testing_path }}
       run: terraform apply -auto-approve -var "unix_interpreter=/bin/dash"
     - name: Check for Failure
-        if: steps.applyu-dash.outcome != 'failure'
-        run: |
-          echo "Apply succeeded when it was expected to fail"
-          exit 1
+      if: steps.applyu-dash.outcome != 'failure'
+      run: |
+        echo "Apply succeeded when it was expected to fail"
+        exit 1
 
     # Apply the Terraform config without specifying a shell
     - name: Terraform Apply
